[mypy]
python_version = 3.10
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[mypy-hdbscan.*]
ignore_missing_imports = true

[mypy-sklearn.*]
ignore_missing_imports = true

[mypy-sentence_transformers.*]
ignore_missing_imports = true

[mypy-supabase.*]
ignore_missing_imports = true